bin/stencil-bundle
lib/bundleValidator.js
package.json

* Add ESLint support for the bundle validations. Overall this will improve the code quality of bundled themes.
@sherrybc @mcampa @bc-ejoe

Merc 97 cyclomatic complexity

---

server/plugins/Renderer/responses/rawResponse.js

MERC-366 append finishorder css

---

bin/stencil-bundle
lib/langAssembler.js

Allow themes that do not support translations and have no lang folder to be bundled successfully.
EAT-727
@mcampa @mickr

Allow bundles without lang folders

---

package.json
server/plugins/Renderer/responses/pencilResponse.js

@hegrec @mickr 
Stapler change:
https://github.com/bigcommerce/stapler/pull/332

MERC-586 Bug fix: stencil-cli was using the wrong variable

---

lib/stencilBundle.js
test/bin/stencil-bundle.spec.js

MERC-497 - Append json directly to archive.
@mcampa

MERC-497 - Append manifest.json directly to archive.

---

LICENSE
README.md
bin/stencil
bin/stencil-start
package.json
server/lib/show-logo.js
server/plugins/renderer/renderer.module.js
test/_mocks/themes/valid/config.json

@bc-ejoe @mcampa @mickr @bc-julianleong @sherrybc

Update naming convention

---

package.json

Bump paper

---

lib/css-assembler.js
lib/template-assembler.js

MERC-683 - Convert sass imports to unix filenames

MERC-683 - Convert sass imports to unix

---

lib/css-assembler.js
lib/template-assembler.js

MERC-758 - Revert MERC-683

---

server/plugins/renderer/responses/redirect-response.js

Redirects not working when transfer-encoding is present in the headers

---

lib/stencil-bundle.js
lib/template-assembler.js

MERC-758
* Template-assembler fix for windows

MERC-758 - Fix paths for templates on Windows

---

package.json

angular-gettext npm fix

---

package.json

MERC-907 paper version bump

---

server/plugins/renderer/renderer.module.js
server/plugins/router/router.module.js

Fixes:
- Stencil CLI should support page names with and without the trailing slash
- Incorrect name of custom directory
@sherrybc

MERC-991 & MERC-992 custom templates lookup fix

---

README.md

No LESS supported

---

bin/stencil-bundle
bin/stencil-init
bin/stencil-start
lib/version-check.js
package.json

- Require a newer version of node before running
- and bumping the version
@lord2800

Require a newer version of node before running

---

server/plugins/renderer/renderer.module.js
server/plugins/renderer/responses/raw-response.js
server/plugins/renderer/responses/raw-response.spec.js
server/plugins/router/router.module.js

This PR should enable Stencil CLI to render `Optimized Checkout` correctly and inject the `optimized-checkout.css` file when modified.
@mcampa @lord2800

Checkout 698 - Enable styling of UCO via Stencil CLI

---

package.json

paper version bump

---

package.json
server/plugins/renderer/renderer.module.js

Remove the session id from the context. This prevents sass compilation in the CLI

---

lib/privateThemeConfig.schema.json
lib/themeConfig.schema.json

https://jira.bigcommerce.com/browse/MERC-1426

MERC-1426 - validation for read_only_files

---

lib/jspm-assembler.js
lib/stencil-init.js
package.json

Fixes an error when running stencil init if a file `assets/js/bundle.js` exist
related to https://jira.bigcommerce.com/browse/MERC-1471
@sherrybc @lord2800

MERC-1494 JSPM bug fix

---

.gitignore
lib/privateThemeConfig.schema.json
lib/themeConfig.schema.json

MERC-1579: Add a new feature customized_checkout to support UCO checkout

---

package.json
server/plugins/renderer/responses/redirect-response.js
server/plugins/stencil-editor/stencil-editor.module.js

transform bcapp secure cookies to non-secure cookies
Site-wide HTTPS causes local Theme Editor to get stuck loading when using Stencil-CLI
@lord2800 @mjschock

MERC-1633 transform bcapp secure cookies to non-secure cookies

---

package.json
server/plugins/renderer/responses/raw-response.js
server/plugins/renderer/responses/raw-response.spec.js

https://jira.bigcommerce.com/browse/STENCIL-2941
@lord2800 @mjschock

STENCIL-2941 Fix an bug that corrupted images

---

README.md
bin/stencil-start

@lord2800 @mattolson @mjschock

STENCIL-2524 Update readme file

---

lib/release/release.js

STENCIL-2554 fix regex issue

---

lib/release/questions.js
lib/release/release.js
package.json

STENCIL-3000 parse changelog and add notes to the release

---

lib/release/release.js

STENCIL-3000 add new draft

---

server/plugins/stencil-editor/api/getVariations.js

https://jira.bigcommerce.com/browse/STENCIL-3070

STENCIL-3070 - Expose config version

---

README.md
webpack.config.js

I started reading the readme and noticed a lot of things that could be cleaned up or polished.
Also, webpack.config.js seemed to have an unused import and a few formatting errors.

Readme cleanup

---

package.json

Bump minor version for custom feature feature.

Bump minor version for custom feature feature

---

package.json

* this is a bump of Paper to the latest version

STENCIL-3323 - Point to new version of Paper

---

bin/stencil-start

- Fixes: https://github.com/bigcommerce/stencil-cli/issues/284
Jira: https://jira.bigcommerce.com/browse/STENCIL-3480

STENCIL-3480 Simplify and fix BrowserSync css reload issue

---

lib/stencil-init.js

Fix link to docs

---

.gitignore
README.md
bin/stencil
bin/stencil-push
bin/stencil-start
lib/build-config.js
lib/build-config.spec.js
lib/stencil-bundle.js
lib/stencil-push.js
lib/stencil-push.spec.js
lib/stencil-push.utils.js
lib/stencil-push.utils.spec.js
lib/theme-api-client.js
lib/theme-config.spec.js
package.json
test/_mocks/bin/dotStencilFile.json

* implements `stencil push` command to bundle and upload a theme
* provides the option to apply the theme
* prompts for the deletion of existing private themes if the theme limit has been reached
* [STENCIL-3046](https://jira.bigcommerce.com/browse/STENCIL-3046)
cc @bigcommerce/stencil-team

STENCIL-3046 - Stencil Push

---

lib/stencil-bundle.js

remove createdAt from the manifest
@pedelman

MERC-2616 remove createdAt from the manifest

---

package.json

Update browser sync repo

---

README.md

Discussed here:
Update to the docs to include required version of the Node runtime
- [Failed install issue](https://github.com/bigcommerce/stencil-cli/issues/374#issuecomment-379076792)

Update README.md to include min versions of Node

---

package.json

* Bring in paper 2.0.8
* Bump version to 1.14.2

Update paper & bump version

---

.travis.yml
appveyor.yml
package.json

Deprecate support for node 4.x
@bigcommerce/storefront-team @bigcommerce/platform-engineering

Deprecate support for node 4.x

---

lib/themeConfig.schema.json

Add support for card management to the theme features supported list.
@bigcommerce/stencil-team @junedkazi

PROJECT-1897: Card Management - List, Delete, Edit, Add Cards

---

package.json

Update stencil-paper version and npm version

update paper-stencil version and npm version

---

lib/themeConfig.schema.json

add csrf protection to the list of valid features

feat(theme): add csrf protection to the list of valid features

---

gulpfile.js
package-lock.json
package.json

updated paper to 2.0.11 + checked package-lock

docs: updated paper to 2.0.11 + checked package-lock

---

README.md

docs: Update stencil cli installation doc

---

package-lock.json
package.json

ci: updated paper to 2.0.12

---

package-lock.json

added browser-sync to package-lock

fix: added browser-sync to package-lock

---

package.json

Updated engine for node in package.json
https://jira.bigcommerce.com/browse/STRF-6713

STRF-6713 CLI: Update engines in package.json

---

package-lock.json
package.json

STRF-6687
Change default behavior of {{getFontsCollection}} to use font-display: swap; for Google Fonts, allow configuration
- [Link 1](https://jira.bigcommerce.com/browse/STRF-6687)

strf: 6687 update stencil-paper

---

.travis.yml
appveyor.yml
package-lock.json
package.json

Remove Node 6 from Travis

---

package-lock.json
package.json

Bump paper to 2.0.18 to pull in latest changes to handlebars helpers.

feat: bump paper to 2.0.18

---

.eslintrc
package-lock.json
package.json
server/plugins/renderer/renderer.module.js
server/plugins/renderer/responses/pencil-response.js

Pull request to bring into paper 3.x branch to stencil-cli
Related to this pr: https://github.com/bigcommerce/stencil-cli/pull/500
- [Link 1](https://jira.bigcommerce.com/browse/STRF-7393)

 feat: strf-7393 make cli work with paper 3.x branch

---

package-lock.json
package.json

pr to update paper in order to fix translation issue that occurs in safari.
- [Link 1](https://jira.bigcommerce.com/browse/STRF-7438)

update paper to 3.0.0-rc.26

---

lib/themeConfig.schema.json

add account_payment_methods_v2 to theme config schema in order to release Cornerstone 4.4.0
- [Link 1](https://jira.bigcommerce.com/browse/STRF-7903)

fix: add account_payment_methods_v2 to theme config schema

---

package-lock.json
package.json

remove express as a dependency since it is not used

feat(dependencies): remove express as a dependency since it is not used

---

package-lock.json
package.json

remove install as a dependency since it is not used

feat(dependencies): remove install as a dependency since it is not used

---

package-lock.json
package.json

remove compression as a dependency

feat(dependencies): remove compression as a dependency

---

bin/stencil-start
lib/css-assembler.js
package-lock.json
package.json
test/_mocks/build-config/legacy-config/stencil.conf.js
test/_mocks/build-config/noready-config/stencil.conf.js
test/_mocks/build-config/valid-config/stencil.conf.js

Remove less as a dependency and some lingering code around it.

fix: remove less dependency and ref since it is not supported or used

---

bin/stencil-bundle
bin/stencil-start
package-lock.json
package.json

update browser sync to use latest master

feat: update browser sync to use latest master

---

package-lock.json
package.json

feat: update colors dependency

---

package-lock.json
package.json

upgrade lodash dependency. I have checked for all breaking change between 3.x and 4.x and it looks safe to upgrade since we don't use any of those functions.
https://github.com/lodash/lodash/wiki/Changelog#v400

feat: upgrade lodash dependency

---

package-lock.json
package.json

feat: bump paper

---

bin/stencil-start
server/lib/utils.js
server/plugins/renderer/renderer.module.js

fix: address chrome cookie SameSite issue

---

bin/stencil-start

watch storefront config file and publish an event

feat: watch storefront config file

---

lib/stencil-bundle.js
package-lock.json
package.json

Bumped version of the outdated npm module "archiver" to fix security vulnerabilities.
This PR is a part of [STRF-8574](https://jira.bigcommerce.com/browse/STRF-8511) (since there are going to be a lot of updates they will be split into several PRs).

fix: strf-8574 Bump version of "archiver" to fix security issues

---

bin/stencil-bundle.spec.js
bin/stencil-init.spec.js
lib/build-config.spec.js
lib/bundle-validator.spec.js
lib/cycles.spec.js
lib/json-lint.spec.js
lib/regions.spec.js
lib/stencil-download.utils.spec.js
lib/stencil-push.spec.js
lib/stencil-push.utils.spec.js
lib/theme-api-client.spec.js
lib/theme-config.spec.js
lib/validator/schema-translations.spec.js
package-lock.json
package.json
server/lib/utils.spec.js
server/plugins/renderer/renderer.module.spec.js
server/plugins/renderer/responses/raw-response.spec.js
server/plugins/router/router.module.spec.js
tasks/changelog/changelog-generator.spec.js
tasks/changelog/command-executor.spec.js

Bumped version of the outdated npm module "lab" (which was renamed to "@hapi/lab") to fix security vulnerabilities.
The newer version of the npm module got breaking changes in the API, so I had to update the corresponding parts of our code.
This PR is a part of STRF-8574 (since there are going to be a lot of updates they will be split into several PRs).

fix: strf-8574, bump version of "@hapi/lab" to fix security issues

---

package-lock.json
package.json

Bump version of stencil-styles
https://jira.bigcommerce.com/browse/STRF-8582

STRF-8582 Bump stencil-styles version

---

package-lock.json
package.json

Bump paper to bring in latest handlebars versions.
ping @mattolson @junedkazi

feat: bump paper to rc31

---

server/plugins/renderer/renderer.module.js
server/plugins/renderer/responses/pencil-response.js
server/plugins/renderer/responses/pencil-response.spec.js

…config.json
A description about what this pull request implements and its purpose. Try to be detailed and describe any technical details to simplify the job of the reviewer and the individual on production support.
- [Link 1](http://example.com)
- ...
Attach images or add image links here.

feature(storefront): STRF-8629 Update cli to use template engine based on the value stored in config.json

---

bin/stencil-start.js
lib/theme-config.js

On config.json current variant is being reset.
https://jira.bigcommerce.com/browse/STRF-5280

fix: (strf-5280) Multiple themes - Changes to config.json not reflected

---

bin/stencil-bundle.js
bin/stencil-download.js
bin/stencil-init.js
bin/stencil-pull.js
bin/stencil-push.js
bin/stencil-release.js
bin/stencil-start.js
bin/stencil.js
constants.js
gulpfile.js
lib/commander.js
lib/release/release.js
lib/stencil-init.js
lib/stencil-push.utils.js
lib/version-check.js
package-lock.json
package.json
server/plugins/renderer/renderer.module.js

- updated "commander"
- moved common constants to constants.js
STRF-8673

STRF-8673: update "commander"

---

server/plugins/renderer/responses/pencil-response.js
server/plugins/renderer/responses/pencil-response.spec.js

Fix template engine values to have compatibility with theme registry
https://jira.bigcommerce.com/browse/STRF-8630

feat: (strf-8630) fix template engine values

---

.github/workflows/pull_request_review.yml
README.md

Update test badges

---

package.json

Reduce the package size on npm by removing files not necessary for cli
```
npm notice package size:  13.6 MB
npm notice unpacked size: 15.0 MB
```
```bash
$ npm pack && tar -xvzf *.tgz && rm -rf package *.tgz
npm notice
npm notice 📦  @bigcommerce/stencil-cli@3.0.0
npm notice === Tarball Contents ===
npm notice 258B    .editorconfig
npm notice 0       .eslintignore
npm notice 1.8kB   .eslintrc
npm notice 9B      .nvmrc
npm notice 53B     .prettierignore
npm notice 1.6kB   LICENSE
npm notice 45B     test/_mocks/themes/regions/templates/components/dynamic/a.html
npm notice 2B      test/_mocks/themes/valid/templates/components/a.html
npm notice 45B     test/_mocks/themes/regions/templates/components/dynamic/b.html
npm notice 2B      test/_mocks/themes/valid/templates/components/b.html
npm …
```

fix: add file list to package file to ignore tests and cli release code

---

CHANGELOG.md
package-lock.json
package.json

docs(release): releasing 3.2.1

---

CHANGELOG.md
package-lock.json
package.json

docs(release): releasing 3.3.0

---

CHANGELOG.md
package-lock.json
package.json

3.4.0-release
Includes changes:
- Support for region translations 
- Support for theme description translations.
-   [MERC-7830 1](https://jira.bigcommerce.com/browse/MERC-7830)

3.4.0-release

---

bin/stencil-release.js
lib/release/questions.js
lib/release/release.js
lib/release/release.spec.js

1. Refactored stencil release to have ability to cover with unit tests
2. Check if version exists in config.json before running stencil release
-   [STRF-9257](https://jira.bigcommerce.com/browse/STRF-9257)

fix: strf-9257 Stencil Release refactoring and version check

---

CHANGELOG.md
package-lock.json
package.json

Releasing 3.4.2 version 
-   [STRF-9257](https://jira.bigcommerce.com/browse/STRF-9257)

docs(release): release 3.4.2

---

.github/workflows/release.yml

Github Action to Release Package through library
-   [STRF-9319](https://jira.bigcommerce.com/browse/STRF-9319)

feat: strf-9319 Github Release for stencil-cli

---

server/plugins/router/router.module.js

This fixes https://github.com/bigcommerce/stencil-cli/issues/760

STRF-9351: fix Stop sending "X-Forwarded-..." headers as it causes remote store to redirect

---

lib/StencilConfigManager.js
lib/StencilConfigManager.spec.js
lib/stencil-init.spec.js

If we don't find an apiHost when loading the stencil config, then log a warning and fallback to `api.bigcommerce.com` as we usually do. This should fix backwards compatibility issues for existing users.
```
➜  cornerstone git:(master) cat config.stencil.json
{
"customLayouts": {
"brand": {},
"category": {},
"page": {},
"product": {}
},
"normalStoreUrl": "https://store-geb0ha4c6c.mybigcommerce.com/",
"port": 3000
}
```
BEFORE:
```
➜  cornerstone git:(master) stencil start
not ok -- Error: Could not fetch a list of the store channels: connect ECONNREFUSED 127.0.0.1:80
Please visit the troubleshooting page https://developer.bigcommerce.com/stencil-docs/deploying-a-theme/troubleshooting-theme-uploads.
If this error persists, please visit https://github.com/bigcommerce/stencil-cli/issues and …
```

feat: strf-9345: Fallback to API_HOST constant in the absense of a provided one

---

bin/stencil-bundle.js
bin/stencil-start.js
lib/BuildConfigManager.js
lib/stencil-bundle.js
lib/stencil-start.js
lib/stencil-start.spec.js

Added a timeout parameter for stencil bundle and stencil start.
-   [STRF-933](https://jira.bigcommerce.com/browse/STRF-9332)

feat: strf-9332 added timeout parameter for stencil bundle command

---

lib/release/questions.js
package-lock.json
package.json

Fixed custom tag creation on `stencil release`
-   [STRF-9375](https://jira.bigcommerce.com/browse/STRF-9375)

fix: strf-9375 Fix custom release tag selection

---

package-lock.json
package.json

Bump Paper to latest from rc52 to rc54.

chore: bump Paper to latest

---

.github/workflows/pull_request_review.yml
.github/workflows/release.yml
CHANGELOG.md
README.md
package-lock.json
package.json

Bump stencil styles to support node 14 

build(release): v3.9.3 dump stencil styles

---

.github/workflows/pull_request_review.yml
package-lock.json

1) package-lock.json wasn't updated in the feature branch
2) run `npm ci` instead of `npm i` on opened PR

fix: package-lock.json and ci workflow

---

CHANGELOG.md
lib/schemas/themeSchema.json

Added sort type to theme schema

feat(payments): paypal-1514 add sort item to theme schema

---

README.md

Added docs how to pull docker stencil-cli and use it locally

docs: added docs for docker pull

---

CHANGELOG.md
package-lock.json
package.json

docs(release): 5.2.1:

---

CHANGELOG.md
package-lock.json
package.json

Release 5.2.1 upd

---

CHANGELOG.md
package-lock.json
package.json

docs(release): release 5.2.2:

---

.github/workflows/pull_request_review.yml
.github/workflows/release.yml
.husky/commit-msg
.releaserc
commitlint.config.js
package-lock.json
package.json

Improve release processes with semantic release: 
- auto bump version
- auto release pr 
- auto github releases
- auto npm publish
-   [STRF-10157](https://bigcommercecloud.atlassian.net/browse/STRF-10157)

feat: STRF-10157 Introduce Semantic Release

---

package-lock.json
package.json

Added missing dependency
-   [STRF-10157](https://bigcommercecloud.atlassian.net/browse/STRF-10157)

fix: STRF-10157 Added missing dependency

---

server/plugins/renderer/renderer.module.js

Mapped URLs do not use their respective templates from custom layouts. 
-   [STRF-10231](https://bigcommercecloud.atlassian.net/browse/STRF-10231)

fix(storefront): strf-10231 Mapped URLs do not use their respective templates:

---

lib/nodeSass/AutoFixer.js
lib/nodeSass/BaseRulesFixer.js
lib/nodeSass/UndefinedVariableFixer.js

Fix with scss autofix script issues, when there are undefined variables in the scss files. 
-   [STRF-10507](https://bigcommercecloud.atlassian.net/browse/STRF-10507)
[STRF-10507]: https://bigcommercecloud.atlassian.net/browse/STRF-10507?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

feat: STRF-10507 Scss autofix issue: Undefined variable

---

lib/nodeSass/AutoFixer.js

fix(storefront): fix typo in AutoFixer

---

package-lock.json
package.json

Bump Stencil Styles
-   [STRF-11740](https://bigcommercecloud.atlassian.net/browse/STRF-11740)
https://github.com/bigcommerce/stencil-styles/pull/94
[STRF-11740]: https://bigcommercecloud.atlassian.net/browse/STRF-11740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: STRF-11740 Inconsistent responses in Stencil CLI Bundle and Theme Editor for scss compilation

---

lib/nodeSass/AutoFixer.js

fix: noop PR

---

package-lock.json
package.json

Bump stencil styles
-   [STRF-11740](https://bigcommercecloud.atlassian.net/browse/STRF-11740)
[STRF-11740]: https://bigcommercecloud.atlassian.net/browse/STRF-11740?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: strf-11740 bump stencil-styles

---

.github/workflows/pull_request_review.yml

Move PR Title to env
-   [STRF-11934](https://bigcommercecloud.atlassian.net/browse/STRF-11934)
[STRF-11934]: https://bigcommercecloud.atlassian.net/browse/STRF-11934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: STRF-11934 Move PR Title to env

---

lib/stencil-push.utils.js

The same as https://github.com/bigcommerce/stencil-cli/pull/1222 with correct commit message
-   [Link 1](http://example.com)
-   ...
Attach images or add image links here.

feat: Show channel IDs in channel prompt when starting dev server

---

.github/workflows/pull_request_title_check.yml
.github/workflows/release.yml

set node 20 for ci:
- release to npm and git 
- PR title check

fix: set node 20 for release

---

README.md

fix: update node version in readme

---

.github/workflows/release.yml
.releaserc
package-lock.json
package.json

- Fixed semantic release PR creation (tested on fork)
- Update the logic for docker tags, so it takes version semver to the tag as well 
-   [STRF-13442](https://bigcommercecloud.atlassian.net/browse/STRF-13442)
[STRF-13442]: https://bigcommercecloud.atlassian.net/browse/STRF-13442?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix: STRF-13442 Fix semantic release PR creation and update docker tags
