bin/stencil-bundle
* Moved createWriteStream to after the error check to prevent a write stream being created even when there is an error.
* Propagted the error to the callback of `Async.series` to handle the failure and throw to stop execution of tasks.
=> MERC-419 - Bundle should not be created on error.

lib/stencil-init.js, server/plugins/renderer/renderer.module.js
MERC-769
When associating a template to a path the trimRight method was trimming off the last letter of the template name if it ended with h t m l individually and trimRight has since been deprecated in lodash.
* Removing lodash trimRight for just a vanilla replace.
* Change generated format for customLayouts object in stencil-init.
=> MERC-769 Custom Templates in Stencil-CLI

server/plugins/renderer/responses/pencil-response.js
@sherrybc 
This fixes the error
```
TypeError: Uncaught error: self.assembler.getTranslations is not a function
```
The paper signature changed and I forgot to update `stencil-cli`
https://github.com/bigcommerce/paper/blob/master/index.js#L25
=> MERC-952 Paper bug fix

lib/stencil-bundle.js, server/plugins/renderer/renderer.module.js
Changes:
- Bug: do not include `manifest.json` file in the bundle. It is auto generated by the bundle process
- Use the default template file for getting front-matter configuration to match production behavior 
MERC-1049 & MERC-1064
@lord2800 @sherrybc
=> MERC-1049 & MERC-1064 bug fixes

server/plugins/renderer/renderer.module.js
When mapping pages to custom templates locally, developers may want to apply a custom template to more than one URL. This PR modifies the matching algorithm to accept either a string URL, or an array of string URLs to match.
If merged, the following would be valid:
```json
{
"customLayouts": {
"product": {
"featured-product.html": ["/special-product-one", "/special-product-two"],
"clearance-product.html": "/clearance-product"
},
"search": {},
"brands": {},
"categories": {}
}
}
```
Also, I'd love to make sure there's tests for this functionality, but I couldn't quite figure out how to expose the render module's internals to a test script. If anyone could point me in the right direction regarding that, I'd be happy to update the PR with tests!
=> Support definition of custom template mappings using an array

lib/jspm-assembler.js, package.json
`stencil bundle` crashes when running `Jspm.bundleSFX()` for no unknown reason.
Downgrading to a known working version while I investigate
@lord2800
=> Downgrade jspm due to crashing when bundling themes

lib/stencil-bundle.js
This PR excludes the folder `assets/cdn` from the zip file created by running `stencil bundle`.
As a theme developer, I might want to include large assets that push the size of my theme's bundle past the 50MB mark. If I want to exclude my assets from the bundle, they'd need to be outside the `assets` directory. This results in the inability to use the stencil server to serve those assets. This change enables the theme developer to use a special folder, named `cdn` within their assets folder which is then excluded from the bundle.
This PR can stand on its own, but I think it makes a lot more sense in the context of my other PR (bigcommerce/paper#97), which enables theme developers to conditionally serve assets from the CDN folder when in a local environment, and from a third-party CDN when …
=> Exclude assets/cdn from stencil bundle

package.json, server/plugins/renderer/responses/pencil-response.js
use's paper's renderTheme method
=> uses paper's renderTheme method

package.json
Fixes an issue with translation syntax errors
@lord2800 
depending on https://github.com/bigcommerce/paper/pull/105/files
=> BIG-29681 stencil-paper version bump

package.json
* Bump `stencil-paper` to 1.2.0
* Please see the release note of [1.2.0](https://github.com/bigcommerce/paper/releases/tag/1.2.0)
* Please refer to the PRs listed [here](https://github.com/bigcommerce/paper/releases/tag/1.2.0)
@bigcommerce/stencil-team @bigcommerce/checkout
=> CHECKOUT-1234: Bump stencil-paper to 1.2.0

package.json
* Bump version to `1.5.0`
To include the following changes (I think? Maybe a good idea to keep a changelog and push git tags for this project as well):
* STENCIL-3000 commit the changelog file #276
* STENCIL-3000 add new draft #277
* STENCIL-3070 - Expose config version #278
* CHECKOUT-1234: Bump stencil-paper to 1.2.0 #279
* Please refer to the relevant PRs.
@bigcommerce/stencil-team @bigcommerce/checkout
=> CHECKOUT-1234: Release v1.5.0

lib/privateThemeConfig.schema.json, lib/themeConfig.schema.json
Add support for google amp to the themes features supported list for validation.
@bigcommerce/stencil-team @mcampa @bookernath
=> STENCIL-2930 Add support for google amp.

server/plugins/stencil-editor/stencil-editor.html
as per title ^
https://jira.bigcommerce.com/browse/CHECKOUT-1553
to always display Optimized Checkout stencil editor panel while in stencil development environment so the user can see all options available in stencil editor
@bigcommerce/checkout @bigcommerce/stencil-team
=> CHECKOUT-1553 always display optimized checkout panel in stencil dev environment

lib/privateThemeConfig.schema.json
We want merchants to be able to view custom features in the detail page for a private theme, if, say, they purchase a private theme from a third-party marketplace that has a non-standard feature listed in the theme metadata there.
We still want marketplace theme features to be validated against a whitelist.
Part of https://jira.bigcommerce.com/browse/STENCIL-3282.
Edited, third time's the charm.
=> Change features schema to array of any non-empty strings

.travis.yml, appveyor.yml, lib/theme-config.spec.js, package.json
This uses the new `@bigcommerce/stencil-styles#1.0.6` which uses a [fork](https://github.com/bigcommerce-labs/node-sass) of `node-sass` compatible with node 6 & 7
Plus, adding AppVeyor for windows tests
=> Add support for Node 6 & 7

server/index.js, server/plugins/renderer/renderer.module.js, server/plugins/stencil-editor/stencil-editor.module.js
Locally, connect the new Storefront Admin bar `CRO-97` redirection to stencil editor
So can test the redirection from localhost:3000 (storefront) to localhost:8181 (stencil editor)
@mcampa @bigcommerce/cp-dt
=> feat(themeEditor): connect stencil editor redirection to stencil editor

package.json
This uses a fork to fix a `browser-sync` bug
I filled a PR on `browser-sync` https://github.com/BrowserSync/browser-sync/pull/1370
As a temporary solution we can merge this while we wait for `browser-sync` to merge and deploy the fix.
https://jira.bigcommerce.com/browse/STENCIL-3429
=> STENCIL-3429 Fix tunnel issue

package.json
This dependency is not used and is showing a warning to users
see https://github.com/bigcommerce/stencil-cli/issues/306
=> Remove eslint-config-airbnb dependency

package.json
Reverts bigcommerce/stencil-cli#307
We going to have to revert this since themes are requiring this dependency from `stencil-cli` because of the way we call `eslint` from the cli codebase.
=> Revert "Remove eslint-config-airbnb dependency"

.gitignore, LICENSE, bin/stencil-bundle.spec.js, bin/stencil-start, lib/stencil-init.js, lib/theme-config.spec.js, package.json, server/index.js, server/lib/stencil-token.js, server/lib/stencil-token.spec.js, server/plugins/renderer/renderer.module.js
* Updates CLI's `init` method to require Client Id and Access Token instead of username and token (but still allows `stencil start` to run if the OAuth credentials aren't present)
* [STENCIL-2984](https://jira.bigcommerce.com/browse/STENCIL-2984)
=> STENCIL-2984 - Replace Basic Auth with OAuth

package-lock.json, package.json
This will allow users to use `stencil-cli` with Node.js 8 only for rendering (`stencil start`)
`stencil bundle` is not working yet due to this issue https://github.com/archiverjs/node-archiver/issues/236
=> stencil-styles version bump for nodejs 8

lib/stencil-init.js
* Allow empty values for clientId and accessToken fields
* so that `stencil init` may be run without entering these fields, in case the manual entry of the Basic Auth credentials is to be done after `init`.
=> Allow empty values for clientId and accessToken fields

bin/stencil-start
* this is a fix for #318 
* the `assemble` method now requires a `templatesFolder` parameter (https://github.com/bigcommerce/stencil-cli/commit/49bcdc6fd79ecf09b70c080a8ea0ae1359d05c57#diff-4d9ab04ab5e144dcef049c51ef7a71fcR21)
cc @bigcommerce/stencil-team @flyingL123
=> Fix for issue #318

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md
See title
To provide consistency in community opened issues and pull requests as well as provide contribution guidelines
=> Add contributing file and github templates

lib/stencil-push.utils.js
* disables active theme deletion attempts by preventing selection of active themes
- [STENCIL-3574](https://jira.bigcommerce.com/browse/STENCIL-3574)
cc @bigcommerce/stencil-team
=> STENCIL-3575 - Don't permit theme deletion of active theme

lib/template-assembler.js, package.json
`template-assembler.js` can cause `stencil build` to exceed the OS limit on open files.
With this change, we rely on [the `graceful-fs` module](https://github.com/isaacs/node-graceful-fs) to correctly handle `EMFILE` errors, by placing them in a queue and retrying when other files are closed.
- Issue #324 
- Issue #335 
- An [unanswered question on SO](https://stackoverflow.com/q/40273512/2014893)
_n/a_
=> fix: avoid EMFILE errors

lib/themeConfig.schema.json
Add Pixelpop to features available to a theme.
Check if it processes the theme when the key is preset.
- [MRKT-359](https://jira.bigcommerce.com/browse/MRKT-359)
- Theme Registry PR: https://github.com/bigcommerce/theme-registry/pull/804
=> MRKT-359 Update Pixel Union Theme Features To Include Pixelpop

lib/css-assembler.js
Currently the css-assembler appends the .scss extension to the files its processing. This is fine in most cases since the default BigCommerce scss imports do not specify an extension. 
There are some frameworks/libraries that do specify the .scss extension such as UIkit(https://getuikit.com/docs/sass). 
If you attempt to import these scss files the cli will throw a file not found error. Removing the extension will resolve this but, you would need to do this for every import statement and every time the framework is updated. This creates extra friction when developing on stencil if you are integrating another framework.
Adding a simple replace regex to remove the .scss extension from an import before trying to find the file allows developers to use both.
Before:
After:
=> adding regex replace to remove .scss extension

lib/stencil-push.utils.js
* replaces a slash if present at the end of the store url so it's allowed and doesn't throw an error
- [STRF-4472](https://jira.bigcommerce.com/browse/STRF-4472)
- https://github.com/bigcommerce/stencil-cli/issues/360
* before
* after
=> STRF-4472 - Allow forward slash in store url

lib/theme-api-client.js, package.json
* Status code 409 is overloaded for two conditions: (1) Private theme count limit (2) Private theme concurrent upload limit.
* Use the error message to disambiguate and present the correct error. This is fragile, but all we have at the moment.
- [STRF-4889](https://jira.bigcommerce.com/browse/STRF-4889)
In the case of two concurrent uploads:
```
Validating theme...
Running ESLint...
SCSS Parsing Started...
Template Parsing Started...
Language Files Parsing Started...
Building Theme Schema File...
Theme task Started...
ok -- Language Files Parsing Finished
ok -- Theme Schema Building Finished
ok -- SCSS Parsing Finished
ok -- Template Parsing Finished
ok -- Theme task Finished
Generating Manifest Started...
ok -- Manifest Generation Finished
ok -- Zipping Files Finished
not ok -- …
```
=> STRF-4889: Fix error message for upload limit

bin/stencil-push, lib/stencil-push.utils.js
Adding `--activate` and `-a` flags to the stencil push command. This will skip the prompts that normally come up asking if you would like to activate the theme and to specify a variation.
You can either specify the variation name after the flag or leave it blank to select the first variation (Light for Cornerstone).
This should resolve issue [364](https://github.com/bigcommerce/stencil-cli/issues/364)
Example of not specifing bundle or theme variation:
Example with bundle zip and variation:
=> Adding -a and --activate flags to stencil push

lib/stencil-bundle.js, package.json
* Bundle all webpack config files. In Cornerstone 2.0, we split these up per environment, so we need to update the pattern used to select files for bundling.
* Bump version to 1.15.0 to prepare for release
- [Jira](https://jira.bigcommerce.com/browse/STRF-4971)
- [Cornerstone issue](https://github.com/bigcommerce/cornerstone/issues/1251)
=> Bundle all webpack files + release 1.15.0

bin/stencil-push, lib/theme-api-client.js, lib/theme-api-client.spec.js
currently if stencil push fails there are no logs that describe the error.
The change is adding error details.
- [Troubleshooting Theme Uploads](https://stencil.bigcommerce.com/docs/uploading-a-custom-theme)
=> log push errors to the console

lib/build-config.js
Detailed description has been written and discussed at issue #379
This change will prevent the issue to happen in most scenarios, if not all.
- [bigcommerce/stencil-cli GitHub issue 379](https://github.com/bigcommerce/stencil-cli/issues/379)
=> Increase timeout for build worker process to be ready

README.md, lib/build-config.js, lib/build-config.spec.js, lib/stencil-bundle.js
Add error handling for the theme's build task. Previously, if an error occurred in the theme's build task (such as Cornerstone's webpack build), we swallow the error and proceed. Additionally, if the task timeout out (took longer than 5 seconds, we'd swallow the error and continue, leading to incomplete bundles.
* Fixes #379 
* Fixes #325
=> Proper error handling for bundle task

server/plugins/theme-assets/theme-assets.module.js
When multiple css/scss files have to be rendered and assembled,
we have to create separate instances of `StencilStyles` since
each `StencilStyles` needs its own file cache for import statements
to work properly.
- [ISSUE 404](https://github.com/bigcommerce/stencil-cli/issues/404)
=> fix: added fix for scss compilation issue

CHANGELOG.md, gulpfile.js, package.json
After starting to check in package-lock.json, we should adjust the gulp task for releasing to run npm install prior the push of the release to github.
=> fix: added npm install to gulp task

server/plugins/renderer/renderer.module.js, server/plugins/renderer/responses/pencil-response.js
The base_url and secure_base_url were not available in settings because they had been explicitly removed. This patch adds them using the current stencil web-server host as a value.
https://developer.bigcommerce.com/stencil-docs/stencil-object-model-reference/stencil-objects/global-objects/settings
=> feat: Add support for base_url and secure_base_url

server/plugins/renderer/renderer.module.js, server/plugins/renderer/responses/pencil-response.js
This reverts commit cc3ca084081a1e5d83ce5e3111232757a0e5a991.
`1.15.8` was found to have issues with `Uncaught SyntaxError: Invalid or unexpected token` when loading the homepage through `localhost:3000`. Reverting this commit fixed this issue. That said, we don't yet have all the context for this original change, and will need to revisit this.
=> Revert "feat: Add support for base_url and secure_base_url"

lib/stencil-bundle.js
Description
We need to validate the size of generated parsed/templates and make sure each of them are under 1MB.
We should fail the bundle process and notify on the terminal which generated files are greater than 1MB.
We are seeing a bunch of cases where zip files are under 50MB but the uploads still fail due to generated parsed/templates files greater than 1MB.
https://jira.bigcommerce.com/browse/STRF-6383
=> fix: strf-6383 add check for template size

package-lock.json, package.json
Bringing in latest stencil-paper so that new a new helper (`getImageSrcset`) can be used for local dev.
=> feat: update stencil-paper to add getImageSrcset helper

package-lock.json, package.json
Moving browser-sync back to master to avoid operating on a fork any longer
I am unable to replicate the bug that made us move to a fork in the first place.
=> fix: strf-7023 move browser-sync back to master

.eslintrc, package-lock.json, package.json, server/plugins/renderer/renderer.module.js, server/plugins/renderer/responses/pencil-response.js
Update paper to 3.x branch in order to not have maintenance headaches 
- [Link 1](https://jira.bigcommerce.com/browse/STRF-7175)
=> feat: strf-7175 bump paper to 3.0.0-rc.19

package-lock.json, package.json
Bump paper to 3.0.0-rc20 to pull in this fix: 
https://github.com/bigcommerce/paper-handlebars/commit/0ffd5a1b96e48e2945275be56d3863187a40957f
=> fix: bump paper to 3.0.0-rc20

bin/stencil-init, lib/stencil-init.js
Accept a `--url` and `--token` argument on `stencil init` to make it easier to start stencil with a one-liner. This pre-fills those options you would normally have to enter.
I think we can use this to make a CP feature to make it easier to instantiate stencil-cli.
- [STRF-7240](https://jira.bigcommerce.com/browse/STRF-7240)
=> feat: accept url, token, and port as arguments on stencil init

package-lock.json, package.json
This reverts commit 1e9ded83d00dc650a89dfb5d8831b3d7a5856663, reversing
changes made to 9b4c8f3da2f0f77a6115bd56b1ee885350110e4b.
In this pr https://github.com/bigcommerce/stencil-cli/pull/491 we tried to get to the latest version of browserSync and we thought it was safe to do so as a previous bug was reported as not reproducible.  However, this breaks css hot reloading.  This fixes https://github.com/bigcommerce/stencil-cli/issues/511.  
[STRF-7326](https://jira.bigcommerce.com/browse/STRF-7326)
=> Revert "Merge pull request #491 from bookernath/browser-sync-master"

.travis.yml, README.md, appveyor.yml, package-lock.json, package.json
Updating stencil styles dependency which allows node 10 support.
=> Adding Support for Node 10

package-lock.json, package.json
Bumps the version of `stencil-styles` to 1.2.0 to support flat and nested keys
[MERC-5836](https://jira.bigcommerce.com/browse/MERC-5836)
=> fix: bump stencil-styles to 1.2.0

lib/theme-api-client.js
Updating a docs url that is no longer active.  The docs are for upload/deploy issues of theme.
- [JIRA](https://jira.bigcommerce.com/browse/STRF-7461)
=> Fix: correcting url for deploy issues docs

bin/stencil-bundle.spec.js, bin/stencil-init.spec.js, lib/build-config.spec.js, lib/regions.spec.js, lib/stencil-push.spec.js, server/plugins/router/router.module.js, server/plugins/router/router.module.spec.js
The JWT auth used for [GraphQL Storefront API](https://developer.bigcommerce.com/api-docs/storefront/graphql/graphql-storefront-api-overview) relies on the `origin` header sent by the browser to understand if the request should be allowed. For CLI, this origin was being sent as `localhost`, which was being rejected.
This PR uses CLI's proxying capabilities to overwrite/forge the correct `origin` header for the request so that GraphQL works again.
=> fix: fix origin sent with graphql requests

server/plugins/router/router.module.js
Stencil cli caches get requests for performance optimisation of data requests. A side effect of this causes the response of storefront api calls like `api/storefront/checkout. This causes issues with signIn and signout functionality on all themes that are run using the cli and sending requests within the cache TTL(15 sec as of now). 
Added proxy passthrough for storefront API calls to avoid caching of responses for these requests. 
[Checkout Issue](https://jira.bigcommerce.com/browse/CHECKOUT-4576)
[Checkout sdk discussion](https://github.com/bigcommerce/checkout-sdk-js/issues/422)
=> fix: avoid caching of storefront api responses

lib/stencil-push.utils.js
When trying to push a theme using `stencil push -a "Theme Variation"`, if the theme variation is typed incorrectly or missing, it gives off a cryptic error message -
```TypeError: Cannot read property 'uuid' of undefined```
This PR added a readable error message in the case a theme variation is not found or invalid.
- #459
=> fix: more detailed theme variation error

lib/stencil-bundle.js
Download or bundle the theme, the file `schema.json` appears to be on a single line, the bundling process uses `JSON.stringify`  without any spacing like the other `JSON`
=> fix: schema.json formatting

bin/stencil-push, lib/stencil-push.utils.js
Adding --delete and -d flags to stencil push. This flag will automatically delete the oldest private theme if the upload limit is reached.
https://github.com/bigcommerce/stencil-cli/issues/429
Before:
After:
=> feat: add flag to auto-delete oldest theme during stencil push

package-lock.json, package.json
Bump paper to 3.0.0-rc.27 to pull in `encodeHtmlEntities` helper
Tests and will test locally.
=> feat: bump paper to 3.0.0-rc.27

lib/release/questions.js, package.json
Remove direct dependency for dateformat npm package. Also switching the date format for changelog from `yyyy-mm-dd` to `mm-dd-yyyy`.
Attach images or add image links here.
=> feat(dependencies): remove dateformat as a direct dependency

package-lock.json, package.json
remove script-loader as a direct dependency since it is not used and it is deprecated https://github.com/webpack-contrib/script-loader
=> feat(dependencies): remove script-loader as a direct dependency

package-lock.json, package.json
remove decompress-zip as a dependency
```
juned.kazi at C02WF0AQHTDH in ~/Codebases/stencil-cli on remove-decompress-zip▲
$ npm ci
npm WARN prepare removing existing node_modules/ before installation
> uws@9.14.0 install /Users/juned.kazi/Codebases/stencil-cli/node_modules/uws
> node-gyp rebuild > build_log.txt 2>&1 || exit 0
> fsevents@1.2.7 install /Users/juned.kazi/Codebases/stencil-cli/node_modules/fsevents
> node install
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.10.3
node-pre-gyp info using node@10.16.3 | darwin | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/Users/juned.kazi/Codebases/stencil-cli/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node" (not found) …
```
=> feat(dependencies): remove decompress-zip as a dependency

bin/stencil-start
tunnel issues and add support for tunnel names
```
$ ~/Codebases/stencil-cli/bin/stencil start
Local: http://localhost:3000
External: http://172.24.101.17:3000
```
```
$ ~/Codebases/stencil-cli/bin/stencil start --tunnel
Local: http://localhost:3000
External: http://172.24.101.17:3000
Tunnel: https://fuzzy-wasp-30.localtunnel.me
```
```
$ ~/Codebases/stencil-cli/bin/stencil start --tunnel "my-custom-tunnel"
Local: http://localhost:3000
External: http://172.24.101.17:3000
Tunnel: https://my-custom-tunnel.localtunnel.me
```
```
$ ~/Codebases/stencil-cli/bin/stencil start --tunnel="my-custom-tunnel-with-equal"
Local: http://localhost:3000
External: http://172.24.101.17:3000
Tunnel: https://my-custom-tunnel-with-equal.localtunnel.me
```
=> fix: tunnel issues and add support for tunnel names

.travis.yml, appveyor.yml, package.json
drop node 8 support since it is EOL https://github.com/nodejs/Release#end-of-life-releases
=> feat: drop node 8 support since it is EOL

package-lock.json, package.json
remove hapi as a direct dependency. It is required in the context of glue and we load it as a dependency for it. So we don't need it to be a hardcoded dependency.
=> feat: remove hapi as a direct dependency

README.md
update readme to reflect node 8 is no longer supported
=> fix: update readme to reflect node 8 is no longer supported

package-lock.json, package.json
add hapi as a direct dependency to lock down hapi version. This is to fix issue #577.
lock generated using the command
```
npm cache clean --force && rm -rf node_modules && rm -f package-lock.json && npm install
```
=> fix: add hapi as a direct dependency to lock down hapi version

lib/release/release.js, package-lock.json, package.json
Bumped version of the outdated npm module "github" (which was renamed to "@octokit/rest") to fix security vulnerabilities.
The newer version of the npm module had a lot of braking changes, so I had to update our core as well (the first commit).
Also refactored the related JS file to use async/await instead of callbacks (the second commit).
This PR is a part of [STRF-8574](https://jira.bigcommerce.com/browse/STRF-8511) (since there are going to be a lot of updates they will be split into several PRs).
=> fix: strf-8574, bump version of "github" package to fix security issues + refactor the related JS file

.eslintrc, bin/stencil-download.js, bin/stencil-init, bin/stencil-init.spec.js, lib/release/questions.js, lib/release/release.js, lib/stencil-init.js, lib/stencil-push.utils.js, package-lock.json, package.json
Bumped version of the outdated npm module "inquirer" to fix security vulnerabilities.
The newer version of the npm module lost the support of callbacks, so I had to update the corresponding parts of our code to use async/await instead of callbacks (the second commit).
Also, updated .eslinrc to allow newer JS syntax, esp. _Object spread operator_ which is supported by NodeJS v10 (the first commit).
This PR is a part of STRF-8574 (since there are going to be a lot of updates they will be split into several PRs).
=> fix: STRF-8574, bump version of "inquirer" package to fix security issues + update .eslintrc

lib/stencil-init.js, lib/theme-config.js, lib/theme-config.spec.js, package.json, server/index.js, server/plugins/renderer/renderer.module.js, server/plugins/router/router.module.js, server/plugins/theme-assets/theme-assets.module.js
Replaced usages of npm module "hoek" with "lodash" to avoid supporting 2 similar libraries.
Did it since "hoek" had security vulnerabilities and required updating the library to newer major versions anyway.
This PR is a part of STRF-8574 (since there are going to be a lot of updates they will be split into several PRs).
=> fix: strf-8574, remove redundant dependency "hoek"

package-lock.json, package.json, server/config.js, server/manifest.js
These modules are deprecated so should have been dropped.
They weren’t actually used:
- we didn’t log each incoming server request;
- everything else (e.g. 500 errors, unhandled rejections) just goes to the console.
So I just removed them. 
https://jira.bigcommerce.com/browse/STRF-8606
=> refactor: strf-8606; removed unused modules "good", "good-console"

lib/bundle-validator.js
Properly log out to the console if there is an unused translation key.
Schema Translation errors do not log to the console properly, making it difficult to debug what the actual issue is when you go to bundle a theme. This pull request allows for the correct translation error to log out by addressing a JavaScript error.
[609](https://github.com/bigcommerce/stencil-cli/issues/609)
=> Resolve Schema Translation Error Logging

package-lock.json, package.json
Bump paper to rc30 to pull in more helpers
New helpers: https://github.com/bigcommerce/paper-handlebars/releases/tag/v4.4.0
=> feat: bump paper to rc30, release 2.2.0

CONTRIBUTING.md, README.md, bin/stencil-init, constants.js, lib/stencil-init.js, lib/stencil-init.spec.js, test/assertions/assertNoMutations.js
Improved code style and test coverage related to the stencil-init CLI command.
This is kinda an example/template on how other CLI commands implementations can be done.
If our team members like this style - other modules can be gradually rewritten in the same way in the future too.
Considered designs:
1) Similar to [/lib/stencil-push.js](https://github.com/bigcommerce/stencil-cli/blob/master/lib/stencil-push.js): One entry function running all the tasks in async.waterfall([...]), each task returns an updated version of the passed options.
- _Advantages_:
- looks more elegant;
- tasks may be shared between different CLI commands since they are pure functions and don’t depend on context (this);
- _Disadvantages_:
- different tasks usually need to work with different variables, which makes …
=> refactor(stencil-init): improve code style and test coverage

bin/stencil-download.js, lib/stencil-download.js, lib/stencil-push.spec.js, lib/stencil-push.utils.js, package-lock.json, package.json
Updated "async" npm package. Figured out that there were almost no breaking changes for us, [apart form one test](https://github.com/bigcommerce/stencil-cli/compare/master...MaxGenash:STRF-8674_update_async?expand=1#diff-1e2ce63b00bff55f2e0bb165bd286bc5R45). While reviewing all the usages of the library I removed redundant usages of async.nextTick. Also, since in async.js v3 all methods return promise if no callback was passed - I removed promisify in ` bin/stencil-download.js`.
Actually, at the moment maojirty (if not all) of the usages of async.js can be replaced with native means (async/await, Promise.all, for...await..of, etc.), but it will take several days, so I didn’t do it here, but we can do it in a separate ticket.
STRF-8674
=> feat: (strf-8674) update "async" npm package

README.md, bin/stencil-download.js, bin/stencil-pull.js, bin/stencil-push.js, lib/cliCommon.js, lib/stencil-download.js, lib/stencil-download.utils.js, lib/stencil-pull.js, lib/stencil-pull.utils.js, lib/theme-api-client.js
Building upon @LordZardeck's work in https://github.com/bigcommerce/stencil-cli/pull/550.
Now `stencil pull` will use the new Theme Configurations API to pull the config, instead of downloading the entire theme and plucking out the file.
Improvements:
- MUCH faster (takes only a second or two)
- Supports multiple storefronts via channel ID
- Supports plucking either the "live" configuration or the "saved" (draft) configuration saved in Page Builder
- Only overwrites `settings` keys in config.json, not the whole file
- If the old behavior is preferred, you can use `stencil download -f config.json`
API changes:
- `--save` argument renamed to `--filename` to avoid confusion with `--saved` (**breaking change**, will go out with 3.0 release)
- New `--channel_id` argument to specify which …
=> feat: update "stencil pull" to use configurations API, improving performance

server/lib/utils.js, server/plugins/renderer/renderer.module.js, server/plugins/renderer/renderer.module.spec.js, server/plugins/renderer/responses/pencil-response.js, server/plugins/renderer/responses/raw-response.js, server/plugins/renderer/responses/redirect-response.js
Fixed bugs in the local server:
1. Local server always returned empty headers because of the typo [in the code](https://github.com/bigcommerce/stencil-cli/compare/master...MaxGenash:STRF-8705_Bug_local_server_is_broken_after_updating_packages?expand=1#diff-596ce37f7ed6dc6ea50288ac9903be41L393) (should be `_.fromPairs(...response.headers.entries())` instead of `_.fromPairs(response.headers.entries())`).
2. Response headers 'set-cookies' were joined into a single string because of [a problem in node-fetch implementation](https://github.com/node-fetch/node-fetch/issues/251) which resulted in parsing the cookies by the browser incorrectly. To avoid it I started using response.headers.raw() which returns an internal raw map of headers.
3. Figured out that fetch handles redirects automatically …
=> fix: (strf-8705) fix broken headers and cookies in local server

server/plugins/renderer/renderer.module.js
Fixed a typo in the code of getTemplatePath method of renderer.module.js.
Reason: there were similar names of the function argument (path) and module-level variable (Path) which got mixed-up after refactoring.
Ticket: STRF-8734
Issue: https://github.com/bigcommerce/stencil-cli/issues/654
=> fix: (strf-8734) fix a typo in renderer.module -> getTemplatePath()

lib/stencil-bundle.js, lib/stencil-start.js, lib/stencil-start.spec.js, lib/utils/fsUtils.js
- Fixed a typo in the code of StencilStart.assembleTemplates(), which caused the bug. Reason: there were similar names of the function argument (path->templatesPath) and module-level variable (Path->path) which got mixed-up after refactoring several PRs ago.
- Covered StencilStart.assembleTemplates() with tests to avoid such bugs in the future.
- Refactored StencilStart.assembleTemplates() and related code to get rid of callbacks and make the testing easier.
Ticket: STRF-8740
Issue: https://github.com/bigcommerce/stencil-cli/issues/656
=> Strf-8740: Bugfix: stencil start yields "...templates are missing..." on themes files updates

.gitattributes, .github/workflows/pull_request_review.yml
in https://github.com/bigcommerce/stencil-cli/pull/648 we moved from Travis+Appveyour to Github actions, but missed the linting step in the new CI/CD config, so I added it back here.
**Upd**: also added .gitattributes to fix problems with prettier on Windows https://stackoverflow.com/a/55998281/9193658 .
And updated the testing step to check test coverage
=> fix: added missed linting step to GitHub actions

lib/release/release.js
- Added missing updating of version in package-lock.json.
- Fixed typo in the code 
- Fixed uploading broken bundle archive (it uploaded just a string with pathname instead of the archive itself) to Github
STRF-6905
=> STRF-6905: stencil release did not update version number in package lock

lib/utils/NetworkUtils.js, lib/utils/NetworkUtils.spec.js
Noticed that after moving to Axios we got a bug that sometimes `stencil push` command fails with a message "not ok – ThemeUploadError: Request body larger than maxBodyLength limit".
To fix the bug I just increased maxBodyLength and maxContentLength to Infinite values.
STRF-8913
=> fix(stencil-push): (STRF-8913) increase maxBodyLength in NetworkUtils.sendApiRequest

lib/stencil-push.utils.js
The --activate flag should allow for the user to specify the theme variation to apply when pushing a theme, e.g. `stencil push --activate Warm` However, the first theme variation is always applied. The variation parameter form the CLI is ignored. 
STRF-8909
BEFORE: The variation specified in the CLI is ignored. The first variation in the list is always applied.
AFTER: The variation specified in the CLI is applied when using the --activate flag
=> fix:(STRF-8909) theme variation not applied with activate flag

lib/release/release.js
Fixed a typo in the code causing a broken changelog after `stencil release` command.
STRF-9011
=> STRF-9011: fix spoiling changelog.md after stencil release command

bin/stencil-pull.js, bin/stencil-push.js, lib/stencil-pull.js, lib/stencil-push.js, lib/stencil-push.utils.js, lib/theme-api-client.js
Updated stencil push and pull commands to support multiple channels.
- feat: [STRF-7651](https://jira.bigcommerce.com/browse/STRF-7651) update push command
- feat: [STRF-8282](https://jira.bigcommerce.com/browse/STRF-8282) - update pull command
`stencil push`
- When there is only 1 channel (skips channel selection):
- When we specify channel_id in arguments (skips channel selection):
- When there are several channels available:
`stencil pull`
- When there is only 1 channel (skips channel selection):
- When we specify channel_id in arguments (skips channel selection):
- When there are several channels available:
=> Updated stencil push and pull commands to support multiple channels

lib/StencilConfigManager.js
There is a typo at an error message displayed to user in the CLI. This pull request fixes it.
N/A
N/A
=> Typo fix at StencilConfigManager.js

lib/utils/NetworkUtils.js, lib/utils/NetworkUtils.spec.js
Added `'x-bc-upstream': 'storefront'` header to support multiple channels in the `start` command because all the CLI requests are handled by Stapler by default and it doesn’t know about channels. 
After this PR `stencil start` command will display a channel whose URL was specified as `normalStoreUrl` in `stencil.config.json`. Previously it always displayed the default channel of the store.
[STRF-9087](https://jira.bigcommerce.com/browse/STRF-9087)
=> fix: (STRF-9087) set upstream=storefront to support multiple channels in start command

lib/stencil-start.js, server/index.js, server/plugins/renderer/renderer.module.js, server/plugins/router/router.module.js
Removed old unused field staplerUrl from the local server. Probably It was used to test local Stapler before cloud-dev-vm appeared.
=> feat: remove old unused field staplerUrl from local server

bin/stencil-start.js, lib/stencil-push.utils.js, lib/stencil-start.js, lib/stencil-start.spec.js, lib/theme-api-client.js, lib/utils/fsUtils.js
- Moved getStoreHash request from stencil-push.utils.js to theme-api-client.js
- Move version check request from stencil-start.js to theme-api-client.js
=> refactor: move API requests from commands to themeApiClient

lib/schemas/schemaTranslations.json
Jira: [MERC-7873](https://jira.bigcommerce.com/browse/MERC-7873)
MERC-7873 Support multiple character language code for schema translations. With the roll out of `TRANS-830.new.language.set`, there are a few languageCodes that are returning as multiple characters, we need to allow the schema validation to accept these new conditions.
This also adds in reserved name space of `i18n.Bigcommerce.` this will be used to translate things not related to the schema settings. 
What the patternProperty checks for:
(1) `^[a-z]{2}` First two letters start with lowercase letter
(2) `(-[a-zA-Z0-9]{2,})` optional `-` + at least 2 length alphanumeric string (could be longer than 2 alphanumerics) 
None
(1) Create dummy `schema_translations.json` (example below)
(2) Upsert locally or can use api 
(3) Expect …
=> MERC-7873 Support multiple character language code for schema translations

lib/schemas/privateThemeConfig.json, lib/schemas/themeConfig.json
feat(other): merc-7834 validate theme variation translations. This will be used to translate the variation config (more specifically variation description). 
[MERC-7834](https://jira.bigcommerce.com/browse/MERC-7834)
Order of release for all PRs:
=> feat(other): merc-7834 validate theme variation translations

lib/content-api-client.js, lib/graphql/query.js, server/index.js, server/lib/page-type-util.js, server/lib/page-type-util.spec.js, server/plugins/renderer/renderer.module.js, server/plugins/renderer/responses/pencil-response.js
Added logic to rendered the widgets in the respective regions of a page. This is done by making GraphQL request for each page request and setting the content via the paper handlebar helper `setContent`.
-   [MERC-7797](https://jiira.bigcommerce.com/browse/MERC-7797)
@junedkazi Would appreciate your input on this PR.
=> feat(other): MERC-7797 Added feature to render Widgets in the regions of supported page types.

lib/regions.js, lib/regions.spec.js, lib/validator/schema-translations.js, package-lock.json, package.json
Note, but build should pass once `paper` PR has been merged and released. Currently build is failing to install packages as I am using a remote url for `paper` package.
Region name localization support. This PR is to add `content-region-translation` data attribute if translation is provided in the html handlebars from the theme. This will be used to surface the correct translation on the front end (page builder) for a particular region.
Steps to test 
(1) Pull down the `storefront-render` [PR](https://github.com/bigcommerce/storefront-renderer/pull/280) and run locally (or can run the container image) 
(2) Pull down `stencil-cli` [PR](https://github.com/bigcommerce/stencil-cli/pull/731) and create theme with `{{{region name="header_bottom" translation="i18n.RegionName.HeaderBottom"}}}` …
=> feat(localization): merc-7830 support for region translations

server/plugins/renderer/renderer.module.js
A description about what this pull request implements and its purpose. Try to be detailed and describe any technical details to simplify the job of the reviewer and the individual on production support.
[MERC-8038](https://jira.bigcommerce.com/browse/MERC-8038)
When we are looking at pages that are not supported by the GraphQL renderedRegions field we were getting back an `undefined` value. This was not accounted for when we were looping over the result. This PR fixes that issue.
=> fix: (MERC-8038) Added check to ensure we are not looping over undefined object

CHANGELOG.md, package-lock.json, package.json
Release 3.4.1 with fix for pages that are not supported by the GraphQL having renderedRegions field as undefined
=> docs(release): releasing 3.4.1

bin/stencil-download.js, bin/stencil-pull.js, bin/stencil-push.js, bin/stencil-start.js, constants.js, lib/stencil-download.utils.js, lib/stencil-init.js, lib/stencil-init.spec.js, lib/stencil-pull.utils.js, lib/stencil-push.utils.js, lib/stencil-start.js
[STRF-9345](https://jira.bigcommerce.com/browse/STRF-9345)
Attempt to infer the apiHost from the storeUrl for integration/staging stores, falling back to API_HOST constant otherwise.
apiHost is now saved in the stencil config and loaded from there instead of just the API_HOST
@jairo-bc
=> feat: strf-9345 Infer apiHost from storeUrl

lib/stencil-init.js, lib/stencil-init.spec.js
Continued from STRF-9345, this should log out the host that we've inferred and set
@jairo-bc @zvuki @bookernath
=> feat: strf-9345: Log api host

CHANGELOG.md, package-lock.json, package.json
Release 3.5.0 
- fix: STRF-9351 Stop sending "X-Forwarded-..." headers as it causes remote store to redirect ([36f5663da](https://github.com/bigcommerce/stencil-cli/commit/36f5663da))
- feat: strf-9303 Replaced jsonlint with parse-json ([b5f16db85](https://github.com/bigcommerce/stencil-cli/commit/b5f16db85))
- feat: strf-9345: Log api host ([51b08a9b2](https://github.com/bigcommerce/stencil-cli/commit/51b08a9b2))
- feat: strf-9345 Infer apiHost from storeUrl ([5b132e90b6](https://github.com/bigcommerce/stencil-cli/commit/5b132e90b6))
- feat: strf-9319 Github Release for stencil-cli ([22949011](https://github.com/bigcommerce/stencil-cli/commit/22949011))
=> docs(release): release 3.5.0

CHANGELOG.md, package-lock.json, package.json
Release 3.5.1
- fix: strf-9345: Fallback to API_HOST constant in the absense of a provided one ([d138536c8](https://github.com/bigcommerce/stencil-cli/commit/d138536c8))
@jairo-bc @bookernath @zvuki @bc-jz
=> docs(release): release 3.5.1

.github/workflows/release.yml
Renamed github workflow on release action
=> fix: strf-9312 Rename github workflow on relaese action

package-lock.json
npm 7 has different package-lock.json format. 
Check carefully _lockfileVersion_, if it's set to 2, it's compatible with previous npm versions.
3 - purely for 7 and higher.
1 - 6 and lower
-   [STRF-9356](https://jira.bigcommerce.com/browse/STRF-9356)
=> fix: strf-9356 Support npm 7 for stencil cli

CHANGELOG.md, package-lock.json, package.json
-   fix: strf-9356 Support npm 7 for stencil cli ([d67747d5384](https://github.com/bigcommerce/stencil-cli/commit/d67747d5384))
=> docs(release): release 3.5.2

package-lock.json
Github Release is [failing](https://github.com/bigcommerce/stencil-cli/runs/3634671397?check_suite_focus=true) because NPM 7 has a bug with installing dependencies using [SSH](https://github.com/npm/cli/issues/2610)
=> fix: strf-9356 Replace ssh to https on node-sass dep

package-lock.json, package.json, server/plugins/theme-assets/theme-assets.module.js
Upgrade stencil styles to 2.1.0, that has dart sass as primary engine for css compilation
[STRF-9040](https://jira.bigcommerce.com/browse/STRF-9040)
=> STRF-9040 Support dart-sass as primary engine for css compilation

CHANGELOG.md, package-lock.json, package.json
-   fix: strf-9375 Fix custom release tag selection ([f41d6dd44fb](https://github.com/bigcommerce/stencil-cli/commit/f41d6dd44fb))
=> docs(release): release 3.6.1

bin/stencil-download.js
I want the ability to run `stencil download` without being prompted about whether to overwrite local files. The goal is to easier be able to run download in my CI pipeline.
This is a conceptual pull requests thus far, I have not verified whether the functionality works exactly as intended. This particular command seemed to be untested, so I did not venture to add any tests.
If you have preferences for how this functionality could work different, please let me know or feel free to make changes.
=> feat: Add overwrite option to download command

package-lock.json
Removed "git+" protocol from node-sass dependencies in package-lock.json
https://github.blog/2021-09-01-improving-git-protocol-security-github/
-   [STRF-9474](https://jira.bigcommerce.com/browse/STRF-9474)
=> fix: strf-9474 Removed "git+" prefix from package-lock

CHANGELOG.md, package-lock.json, package.json
-   fix: strf-9474 Removed "git+" prefix from package-lock ([794](https://github.com/bigcommerce/stencil-cli/pull/794))
=> docs(release): release 3.6.4

CHANGELOG.md, lib/bundle-validator.js, package-lock.json, package.json
-   fix: strf-4307 Frontmatter/yaml validation and trailing symbols checks ([798](https://github.com/bigcommerce/stencil-cli/pull/798))
=> docs(release): release 3.6.5

lib/lang-helper.js, lib/stencil-start.js, lib/store-settings-api-client.js
As a Stencil CLI user,
When I run `stencil start` for a particular store,
I will receive a warning if the store's default shopper language does not have a language file within the theme.
-   [STRF-9245](https://jira.bigcommerce.com/browse/STRF-9245)
=> feat: strf-9245 Warn user if shopper default language file is missing or has missing keys

lib/stencil-start.js, lib/store-settings-api-client.js, server/index.js, server/plugins/renderer/renderer.module.js
Properly apply default shopper language when shopper selection mode is set to use it.
=> fix: strf-9535 Add fallback for shopper language default

lib/stencil-start.js
Noticed a small bug, that should be fixed with this PR. It happens when we delete the default shopper lang file and still try to load it. So moved that check into else condition. 
-   [STRF-9245](https://jira.bigcommerce.com/browse/STRF-9245)
=> fix: strf-9245 don't try to load default shopper lang file, when it doesn't exist

CHANGELOG.md, package-lock.json, package.json
-   fix: strf-9535 Add fallback for shopper language default ([804](https://github.com/bigcommerce/stencil-cli/pull/804))
-   feat: strf-9245 Warn user if shopper default language file is missing or has missing keys ([802](https://github.com/bigcommerce/stencil-cli/pull/802))
-   Bump paper to rc52
Note: BREAKING CHANGE!
In order to get stencil cli working with this version, new Stencil CLI token should be created
=> docs(release): release 3.7.0

lib/lang-assembler.js, lib/lang-assembler.spec.js
During bundle process parsed/lang.json now will have lang keys in lowercase.
-   [STRF-9553](https://jira.bigcommerce.com/browse/STRF-9553)
https://user-images.githubusercontent.com/68893868/145610831-ae9d198c-b640-4edf-900e-5c7e7864a205.mov
=> fix: strf-9553 bundled lang.json has lowercase lang keys

server/plugins/router/router.module.js
Queries to GraphlQL API are broken now. This PR aims to fix by not verifying certificates. 
-   [STRF-9576](https://jira.bigcommerce.com/browse/STRF-9576)
410277-24510a41-4491-4cc3-a395-f6f83c6919dc.png">
=> fix: strf-9576 Fix graphql queries

CHANGELOG.md, package-lock.json, package.json
-   fix: strf-9576 Fix graphql queries ([810](https://github.com/bigcommerce/stencil-cli/pull/810))
-   fix: strf-9553 bundled lang.json has lowercase lang keys ([808](https://github.com/bigcommerce/stencil-cli/pull/808))
=> docs(release): release 3.7.1

package-lock.json, package.json
Updated cheerio version due to https://github.com/jairo-bc/stencil-cli/security/dependabot/package-lock.json/nth-check/open
-   [STRF-9581](https://jira.bigcommerce.com/browse/STRF-9581)
=> fix: strf-9581 Update cheerio version

CHANGELOG.md, package-lock.json, package.json
-   build(deps): bump axios from 0.21.4 to 0.24.0 ([821](https://github.com/bigcommerce/stencil-cli/pull/821))
-   fix: strf-9581 Update cheerio version ([819](https://github.com/bigcommerce/stencil-cli/pull/819))
-   fix: strf-9581 Remove gulp tasks, that are not used anymore ([817](https://github.com/bigcommerce/stencil-cli/pull/817))
=> docs(release): release 3.8.0

CHANGELOG.md, package-lock.json, package.json
-   fix: Updated package.json to use colors 1.4.0 ([827](https://github.com/bigcommerce/stencil-cli/pull/827))
=> docs(release): release 3.8.1

package-lock.json, package.json
Bump stencil styles version with node-sass git protocol fix 
-   [STRF-9600](https://jira.bigcommerce.com/browse/STRF-9600)
=> fix: strf-9600 bump stencil styles version

CHANGELOG.md, package-lock.json, package.json
-   fix: strf-9600 bump stencil styles version ([832](https://github.com/bigcommerce/stencil-cli/pull/832))
=> docs(release): release 3.8.2

CHANGELOG.md, package-lock.json, package.json
-   fix: add activate sass engine name logic ([837](https://github.com/bigcommerce/stencil-cli/pull/837))
=> docs(release): release 3.8.3

CHANGELOG.md, package-lock.json, package.json
-   fix: `stencil init` command including `apiHost` option is now recognized ([830](https://github.com/bigcommerce/stencil-cli/pull/830))
-   feat: `stencil push` command allows to push a theme to multiple channels ([825](https://github.com/bigcommerce/stencil-cli/pull/825))
=> docs(release): 3.8.4

README.md, bin/stencil-push.js, lib/stencil-push.utils.js, lib/stencil-push.utils.spec.js, lib/theme-api-client.js
This feature allows users to apply one theme to multiple storefronts/channels. There are several options available for users:
- `stencil push` command will check whether multiple storefronts/channels available. If yes, user will be prompted to chose one or several/all ids (list of available channels will be shown in radio button style);
- `stencil push -a -c 123 456` allows to apply a theme to selected channels and further system questions will be skipped;
- `stencil push -a -allc` allows to apply a theme to all available channels. 
[STRF-9582](https://jira.bigcommerce.com/browse/STRF-9582)
=> feat(storefront): strf-9582 stencil push: apply theme to multiple storefronts

lib/utils/frontmatter.js, lib/utils/frontmatter.spec.js, test/_mocks/frontmatter/absent.html, test/_mocks/frontmatter/valid.html
Regex to detect frontmatter was causing infinite loop on entry `// ---`
Loosed frontmatter regex to be more simple.
-   [STRF-9594](https://jira.bigcommerce.com/browse/STRF-9594)
=> fix(storefront): strf-9594 loosed frontmatter refex

CHANGELOG.md, package-lock.json, package.json
-   fix(storefront): strf-9594 loosed frontmatter refex ([841](https://github.com/bigcommerce/stencil-cli/pull/841))
=> docs(release): release 3.8.5

package.json
Warn npm users about supported version
https://github.com/bigcommerce/stencil-cli/issues/721#issuecomment-1016884032
=> feat: warn npm users if npm is above 7 version

lib/stencil-push.utils.js, lib/stencil-push.utils.spec.js
After adding the ability to use `stencil-push` to push themes to multiple storefronts, users began reporting an error `not ok -- VariationActivationError: channelIds.map is not a function`
This PR includes a fix to return an iterable from the `promptUserToSelectChannel` method even when a store only has a single storefront. 
- #848 
=> fix: return channel id as an iterable when a store only has a single storefront

CHANGELOG.md, package-lock.json, package.json
- fix: return channel id as an iterable when a store only has a single storefront ([849](https://github.com/bigcommerce/stencil-cli/pull/849))
- feat: warn npm users if npm is above 7 version ([846](https://github.com/bigcommerce/stencil-cli/pull/846))
=> docs(release): release 3.9.0

CHANGELOG.md, package-lock.json, package.json
-   fix: strf-9612 Fix stencil pull when there is 1 channel ([859](https://github.com/bigcommerce/stencil-cli/pull/859))
=> docs(release): release 3.9.1

CHANGELOG.md, package-lock.json, package.json
Release 3.9.2. Contains:
-   chore: bump paper to latest ([863](https://github.com/bigcommerce/stencil-cli/pull/863))
=> build(release): release 3.9.2

.gitattributes, CHANGELOG.md, lib/stencil-bundle.js, server/plugins/theme-assets/theme-assets.module.js
While working on Prelude POC we would like to change new Stencil Theme structure:
- keep SCSS directory under assets but generate css files under `dist/css` dir,
- use regular `css` extension for it.
- use `css_compiler` flag
If we use mentioned structure, `stencil-cli` gives us an error in local development. For this reason we would like to add possibility for `stencil-cli` to work  with  regular css as well as `aseets/scss` directory. On theme side, we will use `css_compiler` flag  from `config.json` that can be switched between `scss` and `css`. On Stencil side we will provide this extension to `CSS Compiler Handler` which then will assemble CSS accordingly.
-   [BCTHEME-1000](https://jira.bigcommerce.com/browse/BCTHEME-1000)
https://user-images.githubusercontent.com/67792608/152140829- …
=> fix(storefront): BCTHEME-1000 handle correctly css extension in stencil

CHANGELOG.md, package-lock.json, package.json
-   chore: bump paper to 3.0.0 ([868](https://github.com/bigcommerce/stencil-cli/pull/868))
=> chore: bump paper to 3.0.0

CHANGELOG.md, package-lock.json, package.json
-   fix(storefront): bctheme-1000 handle regular css in stencil ([845](https://github.com/bigcommerce/stencil-cli/pull/845))
-   chore: bump paper to 3.0.0 ([868](https://github.com/bigcommerce/stencil-cli/pull/868))
=> build(release): 3.10.0

.github/workflows/pull_request_review.yml
Fix CircleCI build for windows, as we had _latest_ version in the setup and VS 2022 is in Preview.
https://github.com/actions/virtual-environments/issues/3949
=> fix: windows circle ci

lib/content-api-client.js
Sometimes, when new theme is applied to the store, I don't receive `regions` object from the API.
cc @bigcommerce/storefront-team, @jkanive
=> fix: when there's no regions on the page

lib/bundle-validator.js, lib/bundle-validator.spec.js, lib/css/compile.js, package-lock.json, package.json, server/plugins/theme-assets/theme-assets.module.js
Scss compilation validation task during theme bundling by running `stencil bundle` command 
-   [STRF-9440](https://jira.bigcommerce.com/browse/STRF-9440)
=> feat: strf-9440 Stencil Bundle: fail on scss failure compilation

lib/css-assembler.js
[It's not possible currently to import raw css files (i.e. from `node_modules`) within a theme](https://support.bigcommerce.com/s/question/0D54O00006yPDn2SAG/include-plain-css-from-nodemodules-in-theme), because `stencil-cli` [provides no such ability](https://github.com/bigcommerce/stencil-cli/blob/master/lib/css-assembler.js#L26).
The standard for importing `.css` files in SCSS is to [not use any extension](https://sass-lang.com/documentation/at-rules/import#importing-css). The proposed change is to check for existence of `.css` file after all other options are exhausted. 
-   [This problem was recognised before](https://support.bigcommerce.com/s/question/0D54O00006yPDn2SAG/include-plain-css-from-nodemodules-in-theme)
=> feat: allow `.css`-files imports within SCSS files

CHANGELOG.md, package-lock.json, package.json
-   bump paper version ([897](https://github.com/bigcommerce/stencil-cli/pull/897))
=> chore: bump paper to 3.0.5

server/index.js, server/plugins/router/router.module.js
Send OAuth token to storefront api paths and graphql
-   [STRF-9718](https://jira.bigcommerce.com/browse/STRF-9718)
=> feat: strf-9718 Add OAuth token to headers

CHANGELOG.md, bin/stencil-bundle.js, bin/stencil-download.js, bin/stencil-init.js, bin/stencil-pull.js, bin/stencil-push.js, bin/stencil-start.js, lib/StencilCLISettings.js, lib/StencilCLISettings.spec.js, lib/cliCommon.js, lib/utils/NetworkUtils.js, lib/utils/NetworkUtils.spec.js
Introduced verbose network requests logging.
-   [STRF-9741](https://jira.bigcommerce.com/browse/STRF-9741)
=> feat: STRF-9741 Verbose error logging in Stencil CLI

CHANGELOG.md, bin/stencil-debug.js, lib/BuildConfigManager.js, lib/StencilDebug.js, lib/StencilDebug.spec.js, package-lock.json, package.json
Introduce `stencil debug` command, that will dump information about the environment: OS, CLI, theme, stencil config. 
-   [STRF-9757](https://jira.bigcommerce.com/browse/STRF-9757)
=> feat: STRF-9757 Add some "stencil debug" command which dumps system info useful for troubleshooting in a user-friendly way

bin/stencil-debug.js, package-lock.json, package.json
Bump simple-git, that is used in release command to provide interface for git commands
-   [STRF-9781](https://bigcommercecloud.atlassian.net/browse/STRF-9781)
=> fix: STRF-9781 Bump simple-git

Dockerfile, README.md
Dockerize stencil cli 
`docker build . -t bc/stencil-cli` (_bc/stencil-cli_ - name of image, it's possible to set any)
`docker run -p 3005:3005  -v /bigcommerce/cornerstone:/usr/src/app -it bc/stencil-cli  stencil start`
`3005` - port from `config.stencil.json`
`/bigcommerce/cornerstone` - path to the theme directory
-   [STRF-9807](https://bigcommercecloud.atlassian.net/browse/STRF-9807)
=> feat: STRF-9807 Dockerize stencil cli

lib/stencil-push.js, lib/stencil-push.utils.js, lib/theme-api-client.js
**UPDATED**
There are 2 bugs behind this issue. 
1. When posting a new theme, it sometimes returns 409 because the theme that was supposed to be deleted is still not done at that point. To resolve this issue, I added `checkIfDeletionIsComplete` to check if the theme deletion is done before uploading a new theme. This will prevent the 409 error that [we saw on kibana](https://kibana.bigcommerce.net/goto/f4662170-d6a3-11ec-877f-6d90996b8d5d). 
As you can see from the screenshot above, it will check if the theme that is supposed to be deleted still exists before pushing a new theme
2. The 409 error above is not caught in the right place, so it fails at the wrong place.
The fix above (adding `checkIfDeletionIsComplete`) will fix this issue automatically, since 409 won't happen when uploading …
=> MERC-8592 Fix stencil CLI Push resulting in intermittent failures

lib/template-assembler.js
With this PR we would like to add opportunity to use templates or styles via external BigCommerce Lib( it will be created later). For this purpose we are going to implement a rule that indicates it's been taken from the external package and not from a directory within a Theme. 
For instance:
`{{> external/bc-ui-lib/templates/carousel-content }}`   **external/** is a flag that template comes from some external lib.
while 
`{{> components/common/carousel-content}}`. is a default way to use html component within a Theme.
-   [BCTHEME-1063](https://jira.bigcommerce.com/browse/BCTHEME-1063)
TBD
=> feat(storefront): bctheme-1063 modify stencil to start locally with components ui library

lib/bundle-validator.js
Currently stencil bundle during scss compilation takes only default settings variables, rather then checking if each of variation is able to compile. This is a temporary fix to grab 1st variation.
-   [STRF-9883](https://bigcommercecloud.atlassian.net/browse/STRF-9883)
=> fix: STRF-9883 Interm fix to grab 1st variation

CHANGELOG.md, lib/stencil-init.js, lib/stencil-init.spec.js
CLI is asking all users which API hostname to use, when this is only necessary for BC employees who want to connect to non-prod.
-   [STRF-9923](https://bigcommercecloud.atlassian.net/browse/STRF-9923)
=> feat(storefront): strf-9923 CLI should not ask users for which API hostname to use:

lib/template-assembler.js
This PR adds ability for theme developers to add components with `@` symbol in the path. 
For this component is required to wrap up its path with `' '` or `" "`
Any other components will work at the same way as it was previously
[BCTHEME-1138](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1138)
=> fix(storefront): bctheme-1138 fix error on import components with @ symbol in the path

lib/StencilConfigManager.js
In situations where several stores are in the same repository, but in different branches, when you change from one branch to another, you always have to enter **accessToken**, which is quite inconvenient. This PR adds the ability to specify the name of the secret file in config.stencil.json, adding flexibility.
Closes #956
=> feat(config): add ability to specify the secret file name

CHANGELOG.md, package-lock.json, package.json
-   fix: STRF-9883 Interm fix to grab 1st variation ([951](https://github.com/bigcommerce/stencil-cli/pull/951))
-   feat(storefront): bctheme-1063 modify stencil to start locally with components ui library ([895](https://github.com/bigcommerce/stencil-cli/pull/895))
-   feat(storefront): bctheme-1064 Modify Stencil bundle for using Components UI Library ([904](https://github.com/bigcommerce/stencil-cli/pull/904))
-   feat: paypal-1514 add sort type to schema ([960](https://github.com/bigcommerce/stencil-cli/pull/960))
-   feat(storefront): strf-9923 CLI should not ask users for which API hostname to use ([955](https://github.com/bigcommerce/stencil-cli/pull/955))
-   fix(storefront): bctheme-1138 fix error on import components with @ symbol in the path …
=> chore: release 5.1.0

CHANGELOG.md, README.md, bin/stencil.js
A description about what this pull request implements and its purpose. Try to be detailed and describe any technical details to simplify the job of the reviewer and the individual on production support.
=> fix: debug command

.github/workflows/release.yml
On release publish docker image with stencil cli in it to Github Packages
-   [STRF-9877](https://bigcommercecloud.atlassian.net/browse/STRF-9877)
https://github.com/bigcommerce/stencil-cli/runs/8058234104?check_suite_focus=true
https://github.com/bigcommerce/stencil-cli/pkgs/container/stencil-cli
=> feat: STRF-9877 Publish stencil cli docker image

CHANGELOG.md, package-lock.json, package.json
-   feat: STRF-9877 Publish stencil cli docker image ([972](https://github.com/bigcommerce/stencil-cli/pull/972))
-   fix: debug command ([970](https://github.com/bigcommerce/stencil-cli/pull/970))
=> chore: release 5.2.0

package-lock.json, package.json, server/index.js, server/plugins/renderer/renderer.module.js, server/plugins/renderer/renderer.module.option2.spec.js, server/plugins/renderer/renderer.module.spec.js
Stencil cli mode is currently disrespect frontmatter in custom templates and uses default FM instead which is what set forth in our documentation. However, customers want stencil logic to fit regular mode logic (respects custom templates FM). Here we add information about custom layouts into headers being sent to bcapp where we process FM logic. This is first part of the task. [Another part](https://github.com/bigcommerce/bigcommerce/pull/48588) is located in `bcapp` repo (where you can find new tested behavior) 
-   [STRF-9832](https://bigcommercecloud.atlassian.net/browse/STRF-9832)
Find screenshots [here](https://github.com/bigcommerce/bigcommerce/pull/48588)
=> feat(storefront): strf-9832 Inconsistent behavior for FM in custom templates:

CHANGELOG.md, package-lock.json, package.json
Reverts bigcommerce/stencil-cli#984 due to package-lock json issues.
=> Revert "docs(release): 5.2.1:"

.github/workflows/release.yml
Fix Github Actions Release by moving registry env var to the specific job, rather than setting on the global level
Issue: https://github.com/bigcommerce/stencil-cli/actions/runs/3126162483/jobs/5071345200 
=> fix(release): registry env var for the release

package-lock.json, server/index.js, server/plugins/renderer/renderer.module.js
Quick-view in stencil-cli mode didn't include `reviews` sections if any.
-   [STRF-9174](https://bigcommercecloud.atlassian.net/browse/STRF-9174)
=> feat(storefront): strf-9174 Product object in quick view on localhost not consistent with prod:

CHANGELOG.md, package-lock.json, package.json
-   fix: STRF-10049 npm 8 install fix ([x](https://github.com/bigcommerce/stencil-cli/pull/x))
=> chore: release 5.2.3

server/plugins/renderer/responses/redirect-response.js
Fix redirects not working locally. Currently, any redirects happening within Stencil CLI will hang, and the redirect will never finish. This can be seen by creating a redirect and attempting to browse to the redirect in Stencil CLI, or by simply attempting to browse to a product without the trailing slash.
We should expect redirects to demonstrate the same behavior that one would see in the production environment of BigCommerce.
This issue was occurring because our `RedirectsResponse.respond` method was not stripping the `'content-length'` header, causing the redirected response to be treated as a stream that would never resolve.
-   [STRF-10118](https://bigcommercecloud.atlassian.net/browse/STRF-10118)
**Before:**
https://user-images.githubusercontent.com/19815878/194952585-25482c58-4d2d- …
=> fix(storefront): strf-10118 Fix redirects stalling locally

CHANGELOG.md, package.json
- fix: STRF-10118 fix redirects stalling locally ([1000](https://github.com/bigcommerce/stencil-cli/pull/1000))
=> docs(release): 5.2.4

CHANGELOG.md, package.json
- fix: STRF-10130 fix 404s on pagination in brands/categories ([1004](https://github.com/bigcommerce/stencil-cli/pull/1004))
=> docs(release): 5.2.5

CHANGELOG.md, lib/template-assembler.js
Currently we experience an error on attempt to use nested templates from external scoped modules due to special symbols .  For instance, if we use some external template in our stencil theme where we re-use some other nested template from external and scoped module (like an UI library with styles and templates) we receive parsing error due to special symbol `@`. We've wrapped  all such nested templates into quotes to prevent this behaviour.
-   [BCTHEME-1284](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1284)
`categories-test` template uses a nested template inside:
cc @bigcommerce/storefront-team, @bigcommerce/themes-team
=> fix(storefront): bctheme-1284 Fix error on using scoped nested external templates

CONTRIBUTING.md
Add instructions/setup steps for creating a local development environment with debugging.
I noticed that we did not have any clear documentation on getting started with developing on a fork of stencil-cli locally. This documentation can be very helpful to future contributors and current members of the storefront team.
-   [STRF-10179](https://bigcommercecloud.atlassian.net/browse/STRF-10179)
n/a
=> docs(storefront): strf-10179 Add environment and debugging setup steps

.github/workflows/pull_request_review.yml, .github/workflows/release.yml, .github/workflows/release_image.yml
1. Bump Github Actions version to v3
2. Divide semantic release and docker image releases.
3. Don't run on merge PR review.
-   [STRF-10157](https://bigcommercecloud.atlassian.net/browse/STRF-10157)
=> fix: STRF-10157 Divide docker image release and semantic

.releaserc, CHANGELOG.md
1. Fix changelog (adjust to the current state).
2. Add tag format, since we don't use v-prefix for the package versioning and tag format. 
=> fix: update changelog and add tag format w/o 'v'

.prettierignore
Disable changelog.md check from prettier, since it's auto-generated 
Came from https://github.com/bigcommerce/stencil-cli/pull/1019
=> fix: disable checking changelog, that was auto-generated

lib/template-assembler.js
In case we re-use  external templates in our UI library and these templates receive data via parameters we will face an issue that we 'loose' these data due to incorrect handling of parameters. This PR fixes issue with incorrect handling of external templates that contain parameters.
-   [BCTHEME-1331](https://bigcommercecloud.atlassian.net/browse/BCTHEME-1331)
Before Fix:
After Fix:
=> fix(storefront): bctheme-1331 Incorrect handling of nested external templates with params

lib/nodeSass/AutoFixer.js, lib/nodeSass/CommaRemovalFixer.js
Comma after or before selectors will cause the theme to fail on compilation 
-   [STRF-10482](https://bigcommercecloud.atlassian.net/browse/STRF-10482)
[STRF-10482]: https://bigcommercecloud.atlassian.net/browse/STRF-10482?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: strf-10482 Bad comma in the selectors

lib/nodeSass/ConditionalImportFixer.js
When a scss file has a conditional import, that it's actually another import and so on, until the last file(s) has(ve) the selectors to be converted into mixins
-   [STRF-10458](https://bigcommercecloud.atlassian.net/browse/STRF-10458)
[STRF-10458]: https://bigcommercecloud.atlassian.net/browse/STRF-10458?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: STRF-10485 Nested multi file import

lib/stencil-push.utils.js
Currently Kibana and CP staff logs are logging variation ID when a theme is applied. Return a variation ID when activating a theme using Stencil CLI so that a developer can match the log with the corresponding variation ID.
https://bigcommercecloud.atlassian.net/browse/MERC-9452
=> fix(storefront): MERC-9452 Return variation id when activating theme

CONTRIBUTING.md
Added documentation section  about Convential Commits on how to contribute to the repo
-   [STRF-10729](https://bigcommercecloud.atlassian.net/browse/STRF-10729)
[STRF-10729]: https://bigcommercecloud.atlassian.net/browse/STRF-10729?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> docs: STRF-10729 Add section about Convential Commits

lib/stencil-pull.js, lib/stencil-pull.utils.js, package-lock.json
Stencil Pull now will always override only variation settings config
-   [STRF-10081](https://bigcommercecloud.atlassian.net/browse/STRF-10081)
Video is too long for Github, so put it on google drive
https://drive.google.com/file/d/1htRCmNgM3u2JqJC-zF0Ib9LgRitnmngK/view?usp=sharing
[STRF-10081]: https://bigcommercecloud.atlassian.net/browse/STRF-10081?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: STRF-10081 stencil pull overrides only variation config

lib/cliCommon.js, lib/cliCommon.spec.js
Currently with some of our scripts this blocks to catch an error, since the error goes to stdout instead of stderr
-   [STRF-11118](https://bigcommercecloud.atlassian.net/browse/STRF-11118)
[STRF-11118]: https://bigcommercecloud.atlassian.net/browse/STRF-11118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: print cli errors to stderr

lib/nodeSass/AutoFixer.js, lib/nodeSass/BaseRulesFixer.js
Fixed and improved couple autofix rules:
- Narrowed bad-comma detection mechanism (previously some cases where detected as bad-comma while they weren't)
- fixed issues with comments in base-level rules  containing parent selector &.
-   [STRF-11281](https://bigcommercecloud.atlassian.net/browse/STRF-11281)
1 case
Before:
After:
2 case: 
Before:
After:
[STRF-11281]: https://bigcommercecloud.atlassian.net/browse/STRF-11281?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: STRF-11281 Narrow comma separation cases and Improve Base Rules Error

server/plugins/router/router.module.js
Correctly add headers indicating this is a stencil cli request to /internalapi routes. This allows us, among other things, to properly set cookies in the browser from checkout when running on localhost.
Before:
We can see cookies are incorrectly coming back with `SameSite=None` which isnt allowed here, so the cookies fail to persist in the browser and no login occurs. We can see internally that the incoming request in this case doesnt have the `stencil-cli` header.
After:
We can see that due to now propagating the header the cookies correctly have empty `SameSite` attribute and persist to the browser allowing login.
=> fix: Properly add stencil-cli headers to internalapi requests

lib/nodeSass/UndefinedVariableFixer.js
Fix regex to detect undefined variable scss error
-   [STRF-11898](https://bigcommercecloud.atlassian.net/browse/STRF-11898)
[STRF-11898]: https://bigcommercecloud.atlassian.net/browse/STRF-11898?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: STRF-11898 fix undefined variable stencil scss autofix

lib/theme-api-client.js
Filter the response from `getStoreChannels()` in `theme-api-client.js` by channel type. Only include `storefront` channels.
This change was requested by users of `stencil-cli` who were finding that the list of URLs given when running `stencil start` or `stencil push` included choices that are not valid. Specifically any channel that is not a "storefront" channel is not a valid choice as there is no template  to display, for example on a marketplace channel that connects to facebook there is no storefront to display.
We are going to filter the list of choices we present to be specifically storefront channels. The changes in this PR are utilized by:
`stencil-start.js`
`stencil-push.js`
`stencil-pull.js`
`stencil-download.js`
**Implementation details**
In order to support filtering the …
=> fix: STRF-11856 - Filter list of channels from getStoreChannels() to storefront channels

lib/theme-api-client.js
This PR handles the possibility of missing the `Channels` auth permission when making a GET for a list of channels in `getStoreChannels()`. 
When [this update](https://github.com/bigcommerce/stencil-cli/pull/1180) was made I overlooked that the standard Stencil CLI auth token that we recommend providing to 3rd parties does not include the "read channel settings" permission by default. So people utilizing the Stencil CLI token, or any v3 token that does not include "read/manage channel settings" permission, can end up with this error when making `start`, `push`, `pull`, or `download` commands:
We will be updating that permission on the Stencil CLI token but people with errors will still have to generate a new token to get this permission. As such, this PR will avoid failures if the …
=> fix: STRF-11923 - Handle Missing a New Channels Permission Requirement in Auth Token

.github/workflows/pull_request_review.yml, .github/workflows/pull_request_title_check.yml, .github/workflows/release.yml, .github/workflows/release_image.yml
Improve workflow by moving Github PR Title check into separate CI job
-   [STRF-11934](https://bigcommercecloud.atlassian.net/browse/STRF-11934)
[STRF-11934]: https://bigcommercecloud.atlassian.net/browse/STRF-11934?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: STRF-11934 Separate Github PR Title check 

server/plugins/renderer/renderer.module.js
When removing multiple coupons, bust the cache because the cart has updated. If we don't the request signature just above this point - https://github.com/bigcommerce/stencil-cli/blob/879019066324c719b623eaf02eb76c26882bec3e/server/plugins/renderer/renderer.module.js#L194 - in the code will be the same as the last and we erroneously return 'cachedResponse2' which is stale.
The request to update the cart is different because it contains the coupon ID, but since it uses  a redirect back to the cart, that request is undifferentiated from the previous request to the cart.php
-   [STRF-11899](https://bigcommercecloud.atlassian.net/browse/STRF-11899)
Before: First coupon removal works as expected, but subsequent removals don't appear to take …
=> fix: STRF-11899 Update cart when multiple coupons are removed

.github/workflows/pull_request_review.yml, package-lock.json, package.json
- Bump stencil paper version
- Drop Node 16 Support
- Add Node 20
-   [STRF-12315](https://bigcommercecloud.atlassian.net/browse/STRF-12315)
[STRF-12315]: https://bigcommercecloud.atlassian.net/browse/STRF-12315?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: STRF-12315 Bump stencil-paper version; BREAKING CHANGE: Drop Node 16 Support

lib/stencil-push.utils.js
Reverts bigcommerce/stencil-cli#1222
Reverting due to incorrect commit message preventing from semantic release creation
=> Revert "Show channel IDs in channel prompt when starting dev server"

package-lock.json, package.json
Semantic release wasn't updated to support ESM
-   [STRF-11834](https://bigcommercecloud.atlassian.net/browse/STRF-11834)
Before:
After:
run `npm run release` locally  -> no ESM errors
[STRF-11834]: https://bigcommercecloud.atlassian.net/browse/STRF-11834?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: semantic release deploy to npm

lib/template-assembler.js, server/plugins/renderer/responses/pencil-response.spec.js, test/_mocks/themes/valid/templates/pages/page3.html
Fixed regex that allows to add partials with syntax `{{#> components/ul }}`
-   [STRF-11523](https://bigcommercecloud.atlassian.net/browse/STRF-11523)
1) Get ready to run stencil start (load theme locally, stencil init, etc.)
2) Run **stencil start**
3) Create a similiar structure of components like [here](https://github.com/bigcommerce/stencil-cli/blob/master/test/_mocks/themes/valid/templates/components/c.html,  [here](https://github.com/bigcommerce/stencil-cli/blob/master/test/_mocks/themes/valid/templates/pages/page.3.html), [here](https://github.com/bigcommerce/stencil-cli/blob/master/test/_mocks/themes/valid/templates/components/li.html) and [here](https://github.com/bigcommerce/stencil-cli/blob/master/test/_mocks/themes/valid/templates/components/ul.html)
4) Observe that list …
=> fix: STRF-11523 Enable dynamic partials

lib/release/release.js
Removing .git extension in the git remote name, so github release API can handle it succesfully 
-   [STRF-12941](https://bigcommercecloud.atlassian.net/browse/STRF-12941)
Before:
After:
[STRF-12941]: https://bigcommercecloud.atlassian.net/browse/STRF-12941?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: STRF-12941 Fix stencil release in case of having .git extension in the remote name

bin/stencil-start.js, lib/stencil-start.js, lib/stencil-start.spec.js
Some users have a proxy or dns settings on the custom domain that block requests from stencil cli. By using --channelUrl you can directly set up bigcommerce domain to bypass custom domain protections
-   [STRF-12622](https://bigcommercecloud.atlassian.net/browse/STRF-12622)
[STRF-12622]: https://bigcommercecloud.atlassian.net/browse/STRF-12622?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: STRF-12941 Add channelUrl parameter to stencil start

lib/stencil-bundle.js
Stencil Bundle does not zip new stencil.conf.cjs file https://github.com/bigcommerce/cornerstone/blob/master/stencil.conf.cjs
=> fix: Add new stencil config file to zip bundle

package-lock.json, package.json
=> fix: bump paper to 5.1.4

lib/BuildConfigManager.js, lib/BuildConfigManager.spec.js, lib/stencil-bundle.js, lib/stencil-start.js
From the recent changes done to support ESM in repo, stencil.conf.cjs was introduced. For the themes that were built with older stencil cli versions, ability to download dev config file from cornerstone repository will help to resolve issues with running locally stencil cli
-   [STRF-13399](https://bigcommercecloud.atlassian.net/browse/STRF-13399)
- Integration tests were added.
[STRF-13399]: https://bigcommercecloud.atlassian.net/browse/STRF-13399?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: STRF-13399 If theme doesn't have stencil.conf.js, download it from cornerstone

.github/workflows/release.yml
use absolute path for docker build and push tag
-   [STRF-12935](https://bigcommercecloud.atlassian.net/browse/STRF-12935)
[STRF-12935]: https://bigcommercecloud.atlassian.net/browse/STRF-12935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: use absolute path for build tag

.github/workflows/release.yml
Manually prepare git tags for docker metadata action
-   [STRF-12935](https://bigcommercecloud.atlassian.net/browse/STRF-12935)
[STRF-12935]: https://bigcommercecloud.atlassian.net/browse/STRF-12935?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> fix: STRF-12935 Fix docker tags

bin/stencil-start.js, lib/stencil-start.js, lib/stencil-start.spec.js
stencil start supports --port that will precede stencil config setting port.
-   [STRF-13448](https://bigcommercecloud.atlassian.net/browse/STRF-13448)
[STRF-13448]: https://bigcommercecloud.atlassian.net/browse/STRF-13448?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> feat: STRF-13448 Support --port for stencil start

package-lock.json, package.json
This PR bumps the `@bigcommerce/stencil-paper dependency` from version 5.2.0 to 5.3.0.
-   [SD-11304](https://bigcommercecloud.atlassian.net/browse/SD-11304)
- Updated `@bigcommerce/stencil-paper` to 5.3.0 in package.json
- Updated `package-lock.json` with the new dependency version
- Stencil Paper 5.3.0 was published on Sept 5 2025  as an experiment cleanup
- This is a minor version bump (5.2.0 → 5.3.0)
[SD-11304]: https://bigcommercecloud.atlassian.net/browse/SD-11304?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> chore: bump @bigcommerce/stencil-paper from 5.2.0 to 5.3.0
